apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<YOUR-MSI-CLIENT-ID>"   # for Managed Identity
    keyvaultName: "my-dev-keyvault"
    objects: |
      array:
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
    tenantId: "fbc92072-2d75-4972-845f-3b8a264b6827"
